#!/usr/bin/python
'''
For all open() calls that strace mentions,
prints unique existing filenames.

Discards the command's stdout
(CONSIDER: our output on stderr)


Also checks whether these files are larger than 1MB,
which is because this was written for something like
  strace-openedfiles ag work_mem
...to see whether it's reading any larrge files it shouldn't
'''

import sys
import os
import re
import subprocess

DEVNULL = open(os.devnull, 'w')

cmd = ['strace','-e', 'trace=open'] + sys.argv[1:]
print "Will run %r"%cmd

p = subprocess.Popen( cmd, stdout=DEVNULL,
                           stderr=subprocess.PIPE )

mentioned = {}

while True:
      line = p.stderr.readline()
      if len(line)==0: # EOF
          break
      m = re.search(r'[(]"(.*?)"[,)] ', line)
      if m:
          filename = m.groups()[0]
          if not filename.startswith('/lib/') and not filename.startswith('/proc/'):
              if filename not in mentioned:
                  mentioned[filename] = True
                  
                  if os.path.isfile(filename): # implicitly ignores non-existing
                      try:
                          stob = os.stat(filename) # (stat not fstat, size of symlinked object if applicable)
                          #print stob.st_size

                          if stob.st_size > 1000*1000:
                              print 'LARGE',filename
                          else:
                              print filename
                      except Exception, e:
                          print e
                          pass
                      
